### ISSUE TITLE
docker中设置时区方法不正确

### ISSUE THREAD

**Issue by yangywcz** [coolmoon327/UESTC-QingShuiHe-SRUN-TELECOM#2]
docker中设置时区应声明环境变量TZ而不是TIME_ZONE

**Comment by coolmoon327** [comment]
感谢提醒，可能这个问题和 issue #1 有关。
我长期运行数月没有出现问题，但是我的宿舍网络走了旁路由的 V2RAY，因此我这边一直没有出现时区或 webdriver 引发的问题。
目前受清水河疫情影响本人不在学校，因此没有条件测试，只能先发布一版未测试的修复 tz + 更新 driver 文件后的 docker。
